Module2 task1
htmlacademy-yii/701371-task-force-1 pull request #6
Opened 2019-11-09 08:58 UTC by Elelion

Планирование – залог успеха

2019-11-15 20:01 UTC, denis-khodakovskiy requested changes

2019-11-15 20:01 UTC, denis-khodakovskiy commented on src/classes/Task.php
> +  const STATUS_NEW = 'new';
А где статус "Провалено"?

2019-11-15 20:01 UTC, denis-khodakovskiy commented on src/classes/Task.php
> +  const ACTION_ABORT = 'abort';
Действий тоже как-то не хватает

2019-11-15 20:01 UTC, denis-khodakovskiy commented on src/classes/Task.php
> +  public function __construct() {}
Зачем пустой конструктор?

2019-11-15 20:01 UTC, denis-khodakovskiy commented on src/classes/Task.php
> +    return 'User action: ' . $this->userAction . PHP_EOL;
Странный метод) Он должен вернуть просто имя действия. Конкатенацию надо выполнять в коде "снаружи"

2019-11-15 20:01 UTC, andrewverner commented on src/classes/Task.php
> +  public function checkStatus(): void
Что это?) Судя по названию, функция должна провести валидацию статуса и вернуть, по логике, булевое значение

2019-11-15 20:01 UTC, andrewverner commented on src/classes/Task.php
> +  public function beginEvent(): void
А это тут зачем?

2019-11-16 19:34 UTC, Elelion commented on src/classes/Task.php
> +  const STATUS_NEW = 'new';
исправлено

2019-11-16 19:42 UTC, Elelion commented on src/classes/Task.php
> +  const ACTION_ABORT = 'abort';
исправлено

2019-11-16 19:44 UTC, Elelion commented on src/classes/Task.php
> +  public function __construct() {}
исправлено

2019-11-16 19:49 UTC, Elelion commented on src/classes/Task.php
> +    return 'User action: ' . $this->userAction . PHP_EOL;
Думал, что конкатенацию можно применять и в return'e. Не знал, что не рекомендуется сие...
Исправлено.

2019-11-16 19:59 UTC, Elelion commented on src/classes/Task.php
> +  public function checkStatus(): void
Не совсем понял замечание, распиши более детальней пожалуйста , что тебе тут не понравилось ?

2019-11-16 20:01 UTC, Elelion commented on src/classes/Task.php
> +  public function beginEvent(): void
Это финальный метод, в котором если все заданные условия будут пройдены, то будет выполняться наш код, который мы разместим туда в дальнейшем из последующих задач.
Говори, что не понравилось тут ? ;)

2019-11-18 19:23 UTC, denis-khodakovskiy requested changes

2019-11-18 19:23 UTC, andrewverner commented on src/classes/Task.php
> +  public $id_executor = null;
camelCase

2019-11-18 19:23 UTC, andrewverner commented on src/classes/Task.php
> +    $this->status = self::STATUS_NEW;
Это тут не надо. В конструктор проще будет передать массив параметров, соответствующих свойствам класса

2019-11-18 19:23 UTC, andrewverner commented on src/classes/Task.php
> +    return self::ACTION_NEW;
Ты превратно понял задачу :) Нужен 1 метод который вернут массив из всех доступных статусов. И такой же 1 метод для всех доступных действий

2019-11-18 19:23 UTC, andrewverner commented on src/classes/Task.php
> +  private function checkStatus($action): void
Убери вообще эту функцию :)

2019-11-18 19:23 UTC, andrewverner commented on src/classes/Task.php
> +  private function beginEvent($action): void
И эту)

2019-11-18 19:23 UTC, andrewverner commented on src/classes/Task.php
> +  public function userAction(string $action): void
И эту тоже)

2019-11-20 06:48 UTC, andrewverner commented on src/classes/Task.php
> +    return 'User action: ' . $this->userAction . PHP_EOL;
Можно, но зачем? Суть ООП в том, что один и тот же метод ты будешь вызывать в разных местах своего приложения. Соответсвенно твой метод олжен вернуть минимум информации. Вся прочая конкатенация в текст должна быть реализована уже там, где ты этот метод вызовешь, но никак не тут

2019-11-22 06:27 UTC, denis-khodakovskiy requested changes

2019-11-22 06:27 UTC, andrewverner commented on src/classes/Task.php
> +  public function __construct(int $idClient, int $idExecutor)
Не. Тоже не совсем то, что надо. Сейчас у тебя достаточно простая модель с 4мя свойствами. А если свойств станет больше? Добавлять в конструктор кучу аргументов - плохой подход. Поэтому лучше передавать в конструктор массив и проверять есть ли свойство в классе через `property_exists`

```
public function __construct(array $data) {
    foreach ($data as $key => $value) {
        if (property_exists($this, $key)) {
            $this->{$key} = $value;
        }
    }
}

$task = new Task([
    'idClient' => 5,
    'idExecutor' => 3,
]);
```

2019-11-22 21:00 UTC, merged