На пути к совершенству
htmlacademy-yii/701371-task-force-1 pull request #8
Opened 2019-11-23 10:15 UTC by Elelion

На пути к совершенству

2019-11-27 06:37 UTC, denis-khodakovskiy requested changes

2019-11-27 06:37 UTC, andrewverner commented on src/components/Action.php
> +// class NewAction extends Action
Убери закомментированный код. В этом файле должно быть только описание класса

2019-11-27 06:37 UTC, andrewverner commented on src/components/Action.php
> +  // **
Что это?)

2019-11-27 06:37 UTC, andrewverner commented on src/components/Action.php
> +  public static function getAction()
`public static function getAction(): string`

2019-11-27 06:37 UTC, andrewverner commented on src/components/AvailableActions.php
> +    foreach (static::getActions() as $action) {
Не стоит использовать `static` там, где можно наверняка использовать `self`

2019-11-27 06:37 UTC, andrewverner commented on src/components/AvailableActions.php
> +      if (!class_exists($action)) {
Оно работает? На все действия описанный в массие у тебя будет ошибка. Классов `new`, `start` и т.д. не существует

2019-11-27 06:37 UTC, andrewverner commented on src/components/CancelAction.php
> +  {
Отформатируй код, чтобы его удобно было читать
```
public static function rightsVerification(
    AvailableActions $availableActions,
    int $userId
): bool
{
```

2019-11-27 06:37 UTC, andrewverner commented on src/components/CancelAction.php
> +      && $availableActions->getIdExecutor() === $userId) {
Что за методы `getCurrentStatus`, `getIdExecutor`? Их реализации в `AvailableActions` нет.

2019-11-27 06:37 UTC, andrewverner commented on src/components/CancelAction.php
> +    }
Вес этот if-else можно упростить через тернарный оператор `?:`

2019-11-27 06:37 UTC, andrewverner commented on src/components/Task.php
> +	// const ACTION_FAIL = 'fail';
Удали то, что перенёс в другие классы. Комменированный код не нужен

2019-11-27 06:37 UTC, andrewverner commented on src/components/Task.php
> +				echo $this->{$key} . PHP_EOL;
А это зачем?) Я понимаю, что это нужно для отладки, но такого кода не должно быть. Хочешь провести отладку - запусти локально, проверь, что рабьотает и убери

2019-11-27 09:38 UTC, Elelion commented on src/components/Action.php
> +// class NewAction extends Action
я его на всякий случай оставил... Ну ок.

2019-11-27 09:48 UTC, Elelion commented on src/components/Action.php
> +  // **
// **
книга: Роберт Мартин - чистый код.

Рекомендует ставить разделяющие комментарии в виде // ** у трудно воспринимаемых ф-ций, и в трудно воспринимаемом коде.

А именно, участок кода:
abstract public static function rightsVerification(
    AvailableActions $AvailableActions,
    int $userId
  ): bool;

не находиться на одной строке, и на ряду с остальными ф-циями лично для меня выглядит более трудно читаемым, а это значит что и для некоторых других разработчиков этот код с разделяющими комментариями будет более легче восприниматься.

Как тебе такое andrewverner наставник ? ))

2019-11-27 09:48 UTC, Elelion commented on src/components/Action.php
> +  public static function getAction()
ок

2019-11-27 09:48 UTC, Elelion commented on src/components/AvailableActions.php
> +    foreach (static::getActions() as $action) {
не знал, ок

2019-11-27 09:50 UTC, Elelion commented on src/components/AvailableActions.php
> +      if (!class_exists($action)) {
точно... поправил , потом проверишь )

2019-11-27 10:03 UTC, Elelion commented on src/components/CancelAction.php
> +  {
Если согласно 4.4. Method Arguments от PSR-2 что ты скинул, то наверное поправил...

2019-11-27 10:04 UTC, Elelion commented on src/components/CancelAction.php
> +      && $availableActions->getIdExecutor() === $userId) {
Они в NewAction и других файлах

2019-11-27 10:06 UTC, Elelion commented on src/components/CancelAction.php
> +    }
Я делал так изначально, но т.к. условие не влазиет в 80 символов на одной строке, читабельность оставлял желать лучшего, по этому сделал через if / else, так понятнее.
Поможешь написать более "красиво" тернарник, буду при много благодарен...

2019-11-27 10:07 UTC, Elelion commented on src/components/Task.php
> +	// const ACTION_FAIL = 'fail';
а вдруг потом скажешь что то переделать и он пригодиться ? А я его грохнул и ищи потом. Разреши грохнуть после того как этот раздел засчитаешь. Ну реально так спокойней и удобней

2019-11-27 11:11 UTC, Elelion commented on src/components/Task.php
> +				echo $this->{$key} . PHP_EOL;
ок...

2019-11-29 20:26 UTC, denis-khodakovskiy requested changes

2019-11-29 20:26 UTC, denis-khodakovskiy commented on src/components/Task.php
> +	// const ACTION_FAIL = 'fail';
Если надо будет переделать, то перенесёшь их обратно. Если руководствоваться такой логикой, то в каждом классе будут куча закомментированного продублированного кода

2019-11-29 20:26 UTC, denis-khodakovskiy commented on src/components/CancelAction.php
> +    }
PSR в помощь)
Если у тебя очень длинное условие из нескольких элементов, то пишут обычно так:
```
if (
    $someVariableWithAVeryLongName1 === $this->someMethodWithAVeryLongName1
    && $someVariableWithAVeryLongName2 === $this->someMethodWithAVeryLongName2
    && $someVariableWithAVeryLongName3 === $this->someMethodWithAVeryLongName3
)
```

2019-11-29 20:26 UTC, denis-khodakovskiy commented on src/components/CancelAction.php
> +      && $availableActions->getIdExecutor() === $userId) {
Они не в NewAction. Ты сначала переименовал Task в AvailableActions, потом вернул всё обратно, а вот `$availableActions` тут забыл поменять обратно на `$task`

2019-11-29 20:26 UTC, andrewverner commented on src/components/AvailableActions.php
> +    return self::RELATIONS_MAP[Action::class] ?? null;
Я опечатался и ты не проверил.
`return self::RELATIONS_MAP[$action::getAction()] ?? null;`

2019-11-29 20:26 UTC, andrewverner commented on src/components/CancelAction.php
> +      && $task->getIdExecutor() === $userId;
Отменить задание может только заказчик и только из статуса "Новое"

```
return $task->getCurrentStatus() === Task::STATUS_NEW
    && $task->idClient === $userId;
```
Проверь условия у каждого класса-действия

2019-11-29 20:26 UTC, andrewverner commented on src/components/NewAction.php
> +class NewAction extends Action
У нас всего 4 действия: "Отменить", "Откликнуться", "Выполнить" и "Отказаться". Этот класс, как и StatusAction - лишние, а вот RespondAction не хватает

2019-11-29 20:26 UTC, andrewverner commented on src/components/Task.php
> +	public function getIdExecutor(): int
Если у тебя свойство idExecutor публичное, то этот метод не нужен, потому как к свойству можно обратиться напрямую через `$task->idExecutor`.
Выбирай: или удалить этот метод, или объявить $idExecutor приватным (как и другие свойства, доступ к которым "напрямую" должен быть закрыт)

2019-11-29 20:26 UTC, andrewverner commented on src/components/AvailableActions.php
> +		self::ACTION_NEW => Task::STATUS_NEW,
Ключами этого массива должны быть имена классов, а не внутренние имена действий. Ты же потом этот массив используешь в getNextStatus, где ищешь в ключах массива имя класса-действия. Т.е. ключи должны быть такими:

```
CancelAction::class => Task::STATUS_CANCELED,
...
```

2019-11-29 20:26 UTC, andrewverner commented on src/components/AvailableActions.php
> +  protected $actions = [];
Если свойство не используется, убери его

2019-12-02 07:12 UTC, denis-khodakovskiy requested changes

2019-12-02 07:12 UTC, andrewverner commented on src/components/AvailableActions.php
> +  const ACTION_NEW = 'new';
Нету такого действия

2019-12-02 07:12 UTC, andrewverner commented on src/components/AvailableActions.php
> +	const ACTION_START = 'start';
И такого тоже нет

2019-12-02 07:12 UTC, andrewverner commented on src/components/AvailableActions.php
> +		NewAction::class => Task::STATUS_NEW,
Такого действия нет

2019-12-02 07:12 UTC, andrewverner commented on src/components/AvailableActions.php
> +		RespondAction::class => Task::STATUS_PROGRESS,
Это единственное действие, которое не должно переводить задание в какой-то статус. По это логике первый же отклик на задание переведёт его в статус "В работе"

2019-12-02 07:12 UTC, andrewverner commented on src/components/AvailableActions.php
> +			self::ACTION_NEW,
Нету такого действия. Где "Откликнуться"?

2019-12-02 07:12 UTC, andrewverner commented on src/components/RespondAction.php
> +    return 'Задание в работе';
"Откликнуться"

2019-12-02 07:12 UTC, andrewverner commented on src/components/FailAction.php
> +    return 'Ой ой, случилось что то ужасное...';
"Отказаться"

2019-12-02 07:36 UTC, Elelion commented on src/components/AvailableActions.php
> +  const ACTION_NEW = 'new';
already noticed

2019-12-02 07:36 UTC, Elelion commented on src/components/AvailableActions.php
> +	const ACTION_START = 'start';
and this too

2019-12-02 07:36 UTC, Elelion commented on src/components/AvailableActions.php
> +		NewAction::class => Task::STATUS_NEW,
ready

2019-12-02 07:36 UTC, Elelion commented on src/components/AvailableActions.php
> +		RespondAction::class => Task::STATUS_PROGRESS,
delete?

2019-12-02 07:36 UTC, Elelion commented on src/components/AvailableActions.php
> +			self::ACTION_NEW,
ready

2019-12-02 07:36 UTC, Elelion commented on src/components/RespondAction.php
> +    return 'Задание в работе';
it's a trifle ... ok...

2019-12-02 07:37 UTC, Elelion commented on src/components/FailAction.php
> +    return 'Ой ой, случилось что то ужасное...';
ok

2019-12-02 07:45 UTC, denis-khodakovskiy requested changes

2019-12-02 07:45 UTC, andrewverner commented on src/components/AvailableActions.php
> +		RespondAction::class => Task::STATUS_PROGRESS,
Да, delete :)

2019-12-02 08:01 UTC, denis-khodakovskiy requested changes

2019-12-02 08:01 UTC, denis-khodakovskiy commented on src/components/CompleteAction.php
> +    return $task->getCurrentStatus() === Task::STATUS_COMPLETED
Это действие никогда не выполнится. Ты пытаешь перевести в статус "Выполнено" уже выполненное задание. Перевести в "Выполнено" можно только из статуса "В работе"

2019-12-02 08:01 UTC, andrewverner commented on src/components/FailAction.php
> +    return $task->getCurrentStatus() === Task::STATUS_FAILED
Это действие никогда не выполнится. Ты пытаешь перевести в статус "Провалено" уже проваленное задание. Перевести в "Провалено" можно только из статуса "В работе"

2019-12-02 09:42 UTC, denis-khodakovskiy requested changes

2019-12-02 09:42 UTC, andrewverner commented on src/components/AvailableActions.php
> +	const ACTION_COMPLE = 'completed';
ACTION_COMPLE**TE**

2019-12-02 09:42 UTC, andrewverner commented on src/components/FailAction.php
> +      && $task->getCurrentIdClient() === $userId;
Отказаться может только исполнитель

2019-12-02 09:42 UTC, andrewverner commented on src/components/RespondAction.php
> +      && $task->getCurrentIdClient() === $userId;
Откликнуться может только исполнитель

2019-12-02 10:37 UTC, merged